In [1]:
using Matching

## Example 2.9

In [10]:
m, n = 5, 4;

In [4]:
m_prefs = [
    1, 2, 3, 4, 0,
    4, 2, 3, 1, 0,
    4, 3, 1, 2, 0,
    1, 4, 3, 2, 0,
    1, 2, 4, 0, 3,
]
m_prefs = reshape(m_prefs, n+1, m)

5x5 Array{Int64,2}:
 1  4  4  1  1
 2  2  3  4  2
 3  3  1  3  4
 4  1  2  2  0
 0  0  0  0  3

In [5]:
f_prefs = [
    2, 3, 1, 4, 5, 0,
    3, 1, 2, 4, 5, 0,
    5, 4, 1, 2, 3, 0,
    1, 4, 5, 2, 3, 0,
]
f_prefs = reshape(f_prefs, m+1, n)

6x4 Array{Int64,2}:
 2  3  5  1
 3  1  4  4
 1  2  1  5
 4  4  2  2
 5  5  3  3
 0  0  0  0

In [7]:
deferred_acceptance(m_prefs, f_prefs)

([1,2,3,4,0],[1,2,3,4])

In [8]:
deferred_acceptance(f_prefs, m_prefs)

([2,3,4,1],[4,1,2,3,0])

## Example 2.17

In [11]:
m = n = 4;

In [12]:
m_prefs = [
    1, 2, 3, 4, 0,
    2, 1, 4, 3, 0,
    3, 4, 1, 2, 0,
    4, 3, 2, 1, 0,
]
m_prefs = reshape(m_prefs, n+1, m)

5x4 Array{Int64,2}:
 1  2  3  4
 2  1  4  3
 3  4  1  2
 4  3  2  1
 0  0  0  0

In [13]:
f_prefs = [
    4, 3, 2, 1, 0,
    3, 4, 1, 2, 0,
    2, 1, 4, 3, 0,
    1, 2, 3, 4, 0,
]
f_prefs = reshape(f_prefs, m+1, n)

5x4 Array{Int64,2}:
 4  3  2  1
 3  4  1  2
 2  1  4  3
 1  2  3  4
 0  0  0  0

In [14]:
deferred_acceptance(m_prefs, f_prefs)

([1,2,3,4],[1,2,3,4])

In [15]:
deferred_acceptance(f_prefs, m_prefs)

([4,3,2,1],[4,3,2,1])

## Example 5.24

In [18]:
m_caps = Array(Int, m)
fill!(m_caps, 2)
f_caps = m_caps

4-element Array{Int64,1}:
 2
 2
 2
 2

In [19]:
deferred_acceptance(m_prefs, f_prefs, m_caps, f_caps)

([1,2,1,2,3,4,3,4],[1,2,2,1,3,4,4,3],[1,3,5,7,9],[1,3,5,7,9])

In [20]:
deferred_acceptance(f_prefs, m_prefs, f_caps, m_caps)

([3,4,3,4,1,2,1,2],[4,3,3,4,2,1,1,2],[1,3,5,7,9],[1,3,5,7,9])

## Page 162

In [21]:
m, n = 7, 5;

In [22]:
s_prefs = [
    5, 1, 0, 2, 3, 4,
    2, 5, 1, 0, 3, 4,
    3, 1, 0, 2, 4, 5,
    4, 1, 0, 2, 3, 5,
    1, 2, 0, 3, 4, 5,
    1, 3, 0, 2, 4, 5,
    1, 3, 4, 0, 2, 6,
]
s_prefs = reshape(s_prefs, n+1, m)

6x7 Array{Int64,2}:
 5  2  3  4  1  1  1
 1  5  1  1  2  3  3
 0  1  0  0  0  0  4
 2  0  2  2  3  2  0
 3  3  4  3  4  4  2
 4  4  5  5  5  5  6

In [24]:
c_prefs = [
    1, 2, 3, 4, 5, 6, 7, 0,
    5, 2, 0, 1, 3, 4, 6, 7,
    6, 7, 3, 0, 1, 2, 4, 5,
    7, 4, 0, 1, 2, 3, 5, 6,
    2, 1, 0, 3, 4, 5, 6, 7,
]
c_prefs = reshape(c_prefs, m+1, n)

8x5 Array{Int64,2}:
 1  5  6  7  2
 2  2  7  4  1
 3  0  3  0  0
 4  1  0  1  3
 5  3  1  2  4
 6  4  2  3  5
 7  6  4  5  6
 0  7  5  6  7

In [26]:
caps = ones(Int, n)
caps[1] = 3
caps

5-element Array{Int64,1}:
 3
 1
 1
 1
 1

In [27]:
deferred_acceptance(s_prefs, c_prefs, caps)

([5,2,3,4,1,1,1],[5,6,7,2,3,4,1],[1,4,5,6,7,8])

In [30]:
deferred_acceptance(s_prefs, c_prefs, ones(Int, m), caps)

([5,2,3,4,1,1,1],[5,6,7,2,3,4,1],[1,2,3,4,5,6,7,8],[1,4,5,6,7,8])

In [29]:
deferred_acceptance(c_prefs, s_prefs, caps, ones(Int, m))

([1,3,4,5,6,7,2],[1,5,1,1,2,3,4],[1,4,5,6,7,8],[1,2,3,4,5,6,7,8])