# Examples

In [1]:
using MatchingMarkets

## Roth and Sotomayor (1990)

### Example 2.9

In [2]:
m, n = 5, 4;

In [3]:
m_prefs = [
    1, 2, 3, 4, 0,
    4, 2, 3, 1, 0,
    4, 3, 1, 2, 0,
    1, 4, 3, 2, 0,
    1, 2, 4, 0, 3,
]
m_prefs = reshape(m_prefs, n+1, m)

5×5 Array{Int64,2}:
 1  4  4  1  1
 2  2  3  4  2
 3  3  1  3  4
 4  1  2  2  0
 0  0  0  0  3

In [4]:
f_prefs = [
    2, 3, 1, 4, 5, 0,
    3, 1, 2, 4, 5, 0,
    5, 4, 1, 2, 3, 0,
    1, 4, 5, 2, 3, 0,
]
f_prefs = reshape(f_prefs, m+1, n)

6×4 Array{Int64,2}:
 2  3  5  1
 3  1  4  4
 1  2  1  5
 4  4  2  2
 5  5  3  3
 0  0  0  0

In [5]:
matching = deferred_acceptance(m_prefs, f_prefs)

MatchingMarkets.Matching(5, 4, 
  [1, 1]  =  true
  [2, 2]  =  true
  [3, 3]  =  true
  [4, 4]  =  true)

In [6]:
matching[1, 2]

false

In [7]:
matching[2, 2]

true

In [8]:
matching[2, :]

4-element SparseVector{Bool,Int64} with 1 stored entry:
  [2]  =  true

In [9]:
matching[:, 1]

5-element SparseVector{Bool,Int64} with 1 stored entry:
  [1]  =  true

In [10]:
matching(1)

1-element Array{Int64,1}:
 1

In [11]:
matching(2, inverse=true)

1-element Array{Int64,1}:
 2

In [12]:
matching = deferred_acceptance(f_prefs, m_prefs)

MatchingMarkets.Matching(4, 5, 
  [4, 1]  =  true
  [1, 2]  =  true
  [2, 3]  =  true
  [3, 4]  =  true)

In [13]:
matching(1)

1-element Array{Int64,1}:
 2

In [14]:
matching(2, inverse=true)

1-element Array{Int64,1}:
 1

In [15]:
get_all_pairs(matching)

Dict{Int64,Array{Int64,1}} with 4 entries:
  4 => [1]
  2 => [3]
  3 => [4]
  1 => [2]

In [16]:
get_all_pairs(matching, inverse=true)

Dict{Int64,Array{Int64,1}} with 5 entries:
  4 => [3]
  2 => [1]
  3 => [2]
  5 => Int64[]
  1 => [4]

### Example 2.17

In [17]:
m = n = 4;

In [18]:
m_prefs = [
    1, 2, 3, 4, 0,
    2, 1, 4, 3, 0,
    3, 4, 1, 2, 0,
    4, 3, 2, 1, 0,
]
m_prefs = reshape(m_prefs, n+1, m)

5×4 Array{Int64,2}:
 1  2  3  4
 2  1  4  3
 3  4  1  2
 4  3  2  1
 0  0  0  0

In [19]:
f_prefs = [
    4, 3, 2, 1, 0,
    3, 4, 1, 2, 0,
    2, 1, 4, 3, 0,
    1, 2, 3, 4, 0,
]
f_prefs = reshape(f_prefs, m+1, n)

5×4 Array{Int64,2}:
 4  3  2  1
 3  4  1  2
 2  1  4  3
 1  2  3  4
 0  0  0  0

In [20]:
matching = deferred_acceptance(m_prefs, f_prefs)

MatchingMarkets.Matching(4, 4, 
  [1, 1]  =  true
  [2, 2]  =  true
  [3, 3]  =  true
  [4, 4]  =  true)

In [21]:
matching(1)

1-element Array{Int64,1}:
 1

In [22]:
matching(2, inverse=true)

1-element Array{Int64,1}:
 2

In [23]:
deferred_acceptance(f_prefs, m_prefs)

MatchingMarkets.Matching(4, 4, 
  [4, 1]  =  true
  [3, 2]  =  true
  [2, 3]  =  true
  [1, 4]  =  true)

### Example 5.24

In [24]:
m_caps = fill(2, m)
f_caps = m_caps

4-element Array{Int64,1}:
 2
 2
 2
 2

In [25]:
matching = deferred_acceptance(m_prefs, f_prefs, m_caps, f_caps)

MatchingMarkets.Matching(4, 4, 
  [1, 1]  =  true
  [2, 1]  =  true
  [1, 2]  =  true
  [2, 2]  =  true
  [3, 3]  =  true
  [4, 3]  =  true
  [3, 4]  =  true
  [4, 4]  =  true)

In [26]:
matching(1)

2-element Array{Int64,1}:
 1
 2

In [27]:
matching(3, inverse=true)

2-element Array{Int64,1}:
 3
 4

In [28]:
deferred_acceptance(f_prefs, m_prefs, f_caps, m_caps)

MatchingMarkets.Matching(4, 4, 
  [3, 1]  =  true
  [4, 1]  =  true
  [3, 2]  =  true
  [4, 2]  =  true
  [1, 3]  =  true
  [2, 3]  =  true
  [1, 4]  =  true
  [2, 4]  =  true)

### Page 162

In [29]:
m, n = 7, 5;

In [30]:
s_prefs = [
    5, 1, 0, 2, 3, 4,
    2, 5, 1, 0, 3, 4,
    3, 1, 0, 2, 4, 5,
    4, 1, 0, 2, 3, 5,
    1, 2, 0, 3, 4, 5,
    1, 3, 0, 2, 4, 5,
    1, 3, 4, 0, 2, 6,
]
s_prefs = reshape(s_prefs, n+1, m)

6×7 Array{Int64,2}:
 5  2  3  4  1  1  1
 1  5  1  1  2  3  3
 0  1  0  0  0  0  4
 2  0  2  2  3  2  0
 3  3  4  3  4  4  2
 4  4  5  5  5  5  6

In [31]:
c_prefs = [
    1, 2, 3, 4, 5, 6, 7, 0,
    5, 2, 0, 1, 3, 4, 6, 7,
    6, 7, 3, 0, 1, 2, 4, 5,
    7, 4, 0, 1, 2, 3, 5, 6,
    2, 1, 0, 3, 4, 5, 6, 7,
]
c_prefs = reshape(c_prefs, m+1, n)

8×5 Array{Int64,2}:
 1  5  6  7  2
 2  2  7  4  1
 3  0  3  0  0
 4  1  0  1  3
 5  3  1  2  4
 6  4  2  3  5
 7  6  4  5  6
 0  7  5  6  7

In [32]:
caps = ones(Int, n)
caps[1] = 3
caps

5-element Array{Int64,1}:
 3
 1
 1
 1
 1

In [33]:
matching = deferred_acceptance(s_prefs, c_prefs, caps)

MatchingMarkets.Matching(7, 5, 
  [5, 1]  =  true
  [6, 1]  =  true
  [7, 1]  =  true
  [2, 2]  =  true
  [3, 3]  =  true
  [4, 4]  =  true
  [1, 5]  =  true)

In [34]:
matching(1)

1-element Array{Int64,1}:
 5

In [35]:
matching(1, inverse=true)

3-element Array{Int64,1}:
 5
 6
 7

In [36]:
get_all_pairs(matching)

Dict{Int64,Array{Int64,1}} with 7 entries:
  7 => [1]
  4 => [4]
  2 => [2]
  3 => [3]
  5 => [1]
  6 => [1]
  1 => [5]

In [37]:
get_all_pairs(matching, inverse=true)

Dict{Int64,Array{Int64,1}} with 5 entries:
  4 => [4]
  2 => [2]
  3 => [3]
  5 => [1]
  1 => [5, 6, 7]

In [38]:
deferred_acceptance(s_prefs, c_prefs, caps, SProposing)

MatchingMarkets.Matching(7, 5, 
  [5, 1]  =  true
  [6, 1]  =  true
  [7, 1]  =  true
  [2, 2]  =  true
  [3, 3]  =  true
  [4, 4]  =  true
  [1, 5]  =  true)

In [39]:
deferred_acceptance(s_prefs, c_prefs, caps, CProposing)

MatchingMarkets.Matching(5, 7, 
  [1, 1]  =  true
  [5, 2]  =  true
  [1, 3]  =  true
  [1, 4]  =  true
  [2, 5]  =  true
  [3, 6]  =  true
  [4, 7]  =  true)

## Gusfield and Irving (1989)

### Section 1.6.5

In [40]:
m, n = 11, 5;

In [41]:
s_prefs = [
    3, 1, 5, 4, 0, 2,
    1, 3, 4, 2, 5, 0,
    4, 5, 3, 1, 2, 0,
    3, 4, 1, 5, 0, 2,
    1, 4, 2, 0, 3, 5,
    4, 3, 2, 1, 5, 0,
    2, 5, 1, 3, 0, 4,
    1, 3, 2, 5, 4, 0,
    4, 1, 5, 0, 2, 3,
    3, 1, 5, 2, 4, 0,
    5, 4, 1, 3, 2, 0,
]
s_prefs = reshape(s_prefs, n+1, m)

6×11 Array{Int64,2}:
 3  1  4  3  1  4  2  1  4  3  5
 1  3  5  4  4  3  5  3  1  1  4
 5  4  3  1  2  2  1  2  5  5  1
 4  2  1  5  0  1  3  5  0  2  3
 0  5  2  0  3  5  0  4  2  4  2
 2  0  0  2  5  0  4  0  3  0  0

In [42]:
c_prefs = [
    3, 7, 9, 11, 5, 4, 10, 8, 6, 1, 2, 0,
    5, 7, 10, 6, 8, 2, 3, 11, 0, 1, 4, 9,
    11, 6, 8, 3, 2, 4, 7, 1, 10, 0, 5, 9,
    10, 1, 2, 11, 4, 9, 5, 3, 6, 8, 0, 7,
    2, 4, 10, 7, 6, 1, 8, 3, 11, 9, 0, 5,
]
c_prefs = reshape(c_prefs, m+1, n)

12×5 Array{Int64,2}:
  3   5  11  10   2
  7   7   6   1   4
  9  10   8   2  10
 11   6   3  11   7
  5   8   2   4   6
  4   2   4   9   1
 10   3   7   5   8
  8  11   1   3   3
  6   0  10   6  11
  1   1   0   8   9
  2   4   5   0   0
  0   9   9   7   5

In [43]:
caps = [4, 1, 3, 2, 1];

In [44]:
matching = deferred_acceptance(s_prefs, c_prefs, caps)

MatchingMarkets.Matching(11, 5, 
  [2 ,  1]  =  true
  [5 ,  1]  =  true
  [8 ,  1]  =  true
  [10,  1]  =  true
  [7 ,  2]  =  true
  [1 ,  3]  =  true
  [4 ,  3]  =  true
  [6 ,  3]  =  true
  [3 ,  4]  =  true
  [9 ,  4]  =  true
  [11,  5]  =  true)

In [45]:
matching(4)

1-element Array{Int64,1}:
 3

In [46]:
matching(1, inverse=true)

4-element Array{Int64,1}:
  2
  5
  8
 10

In [47]:
get_all_pairs(matching)

Dict{Int64,Array{Int64,1}} with 11 entries:
  2  => [1]
  11 => [5]
  7  => [2]
  9  => [4]
  10 => [1]
  8  => [1]
  6  => [3]
  4  => [3]
  3  => [4]
  5  => [1]
  1  => [3]

In [48]:
get_all_pairs(matching, inverse=true)

Dict{Int64,Array{Int64,1}} with 5 entries:
  4 => [3, 9]
  2 => [7]
  3 => [1, 4, 6]
  5 => [11]
  1 => [2, 5, 8, 10]

In [49]:
deferred_acceptance(s_prefs, c_prefs, caps, SProposing)

MatchingMarkets.Matching(11, 5, 
  [2 ,  1]  =  true
  [5 ,  1]  =  true
  [8 ,  1]  =  true
  [10,  1]  =  true
  [7 ,  2]  =  true
  [1 ,  3]  =  true
  [4 ,  3]  =  true
  [6 ,  3]  =  true
  [3 ,  4]  =  true
  [9 ,  4]  =  true
  [11,  5]  =  true)

In [50]:
matching = deferred_acceptance(s_prefs, c_prefs, caps, CProposing)

MatchingMarkets.Matching(5, 11, 
  [4 ,  1]  =  true
  [5 ,  2]  =  true
  [3 ,  3]  =  true
  [1 ,  4]  =  true
  [1 ,  5]  =  true
  [3 ,  6]  =  true
  [2 ,  7]  =  true
  [3 ,  8]  =  true
  [1 ,  9]  =  true
  [4 , 10]  =  true
  [1 , 11]  =  true)

In [51]:
get_all_pairs(matching)

Dict{Int64,Array{Int64,1}} with 5 entries:
  4 => [1, 10]
  2 => [7]
  3 => [3, 6, 8]
  5 => [2]
  1 => [4, 5, 9, 11]

In [52]:
get_all_pairs(matching, inverse=true)

Dict{Int64,Array{Int64,1}} with 11 entries:
  2  => [5]
  11 => [1]
  7  => [2]
  9  => [1]
  10 => [4]
  8  => [3]
  6  => [3]
  4  => [1]
  3  => [3]
  5  => [1]
  1  => [4]

The book claims that the following matching $M_7$ is the hospital-optimal
(college-optimal in our language) stable matching:
$$
\begin{array}
~   & r_1 & r_2 & r_3 & r_4 & r_5 & r_6 & r_7 & r_8 & r_9 & r_{10} & r_{11} \\
M_7 & h_4 & h_4 & h_3 & h_1 & h_1 & h_3 & h_2 & h_3 & h_1 & h_5    & h_1
\end{array}
$$

but the above matching, say $M_8$, appears to be the hospital-optimal matching:
$$
\begin{array}
~   & r_1 & r_2 & r_3 & r_4 & r_5 & r_6 & r_7 & r_8 & r_9 & r_{10} & r_{11} \\
M_8 & h_4 & h_5 & h_3 & h_1 & h_1 & h_3 & h_2 & h_3 & h_1 & h_4    & h_1
\end{array}
$$